;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Duration",DevComment="")
+GameplayTagList=(Tag="Ability.Stunned",DevComment="")
+GameplayTagList=(Tag="AN.Attack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Impact",DevComment="")

